services:
  - type: web
    name: fatho-massoterapia
    runtime: python
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py migrate && \
      mkdir -p staticfiles  # Garante que a pasta existe
      python manage.py collectstatic --noinput
    startCommand: gunicorn fathowebpage.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: fathowebpage.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: fathojf_db
          property: connectionString

databases:
  - name: fathojf_db
    plan: free  # Adicione esta linha
    databaseName: fathojf_db
    user: fathojf_db_user