# Generated by Django 5.1.7 on 2025-04-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sobre a Fatho', max_length=100, verbose_name='Título')),
                ('foto', models.ImageField(upload_to='sobre/', verbose_name='Foto de perfil')),
                ('descricao', models.TextField(verbose_name='Descrição completa')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Sobre',
                'verbose_name_plural': 'Sobre',
            },
        ),
    ]
