# Generated by Django 5.1.7 on 2025-04-17 16:33

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sobre',
            name='descricao',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descrição completa'),
        ),
    ]
