# Generated by Django 5.1.7 on 2025-04-17 01:17

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='tagline',
            field=models.CharField(blank=True, help_text='Frase de efeito para o serviço', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Imagem recomendada: 800x600px (proporção 4:3)', upload_to='services/', validators=[services.models.validate_image_size]),
        ),
    ]
