# Generated by Django 5.1.7 on 2025-04-17 15:30

import services.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_tagline_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(help_text='Imagem recomendada: 400x300px (proporção 4:3)', upload_to='services/', validators=[services.models.validate_image_size]),
        ),
    ]
